### ISSUE TITLE
Hystrix.Dotnet.Samples.AspNetCore not working out of the box

### ISSUE THREAD

**Issue by HigorCesar** [Travix-International/Hystrix.Dotnet#12]
Error message during restore: Unable to resolve 'Hystrix.Dotnet.AspNetCore (>= 1.0.2)' for '.NETCoreApp,Version=v1.1'.				

It seems that the version of the package should be 1.0.0-beta3

**Comment by markvincze** [comment]
Thanks for reporting!

After I merged the 2 PRs pending I'll sort those versions out.
