### ISSUE TITLE
Owin middleware

### ISSUE THREAD

**Issue by klettier** [Travix-International/Hystrix.Dotnet#19]
Hello,

I'm running a self hosted API with **Owin** and have implemented my own **Owin middleware** to replace the **HystrixStreamHandler** that I cannot use without **IIS**.

I would like to make a PR to provide the middleware code in his own project (**Hystrix.Dotnet.Owin**) but it would be great to have the **configuration** parsing shared accross both projects (**Hystrix.Dotnet.AspNet** and **Hystrix.Dotnet.Owin**) and so extracting that logic into another project **Hystrix.Dotnet.WebConfiguration**.

What do you think ?

kévin

**Comment by klettier** [comment]
Any chance to get an update on this ?

**Comment by markvincze** [comment]
Hi @klettier,

Sounds great, it'd be awesome to include this in the library.  
Yep, I agree, the config parsing is complicated enough so that it's worth it to try to avoid duplicating it, extracting it to a common library sounds good to me.
cc @JorritSalverda

**Comment by klettier** [comment]
Nice, [here](https://github.com/Travix-International/Hystrix.Dotnet/compare/master...klettier:feature/owin?expand=1) is where I am, don't hesitate to let me know what you think about it.

I will add the sample soon.

kévin
