### ISSUE TITLE
Implement retry

### ISSUE THREAD

**Issue by markvincze** [Travix-International/Hystrix.Dotnet#2]
When executing operations that can occasionally fail (for example because of flaky network connection), it'd be nice to be able to tell Hystrix to automatically retry.

Configuration per command:
 - Is retry enabled
 - How many times do we retry
 - Wait time between retries

Questions:
 - Increase wait time between subsequent retries? (use Jitter?)
 - Filter the situations in which we retry (for example we retry in case of a timeout, or in case of exceptions related to networking, but we don't retry in case of an `InvalidOperationException`)?

**Comment by JorritSalverda** [comment]
In the original Hystrix they only do a single retry and only for network issues, not if the dependency itself returns an error. More retries are unlikely to fit inside the time limit and kind of defeat the purpose of failing fast for any dependency that's causing problems.

**Comment by markvincze** [comment]
That sounds good to me, ~90% of the errors I see for which a retry would make sense are network hiccups.
