### ISSUE TITLE
Add example for fallback function to README.md

### ISSUE THREAD

**Issue by 1kastner** [Travix-International/Hystrix.Dotnet#20]
I was searching for some explanation how I can set a fallback because I come from the Java version which uses self-written classes, see [the Java version](https://github.com/Netflix/Hystrix/wiki/Configuration#CommandFallback). So when I searched for the fallback I found some information, e.g. in the [HystrixCommand implementation](https://github.com/Travix-International/Hystrix.Dotnet/blob/master/src/Hystrix.Dotnet/IHystrixCommand.cs). It seems like I can just pass some delegate but a nice example for that in the global README.md would be great. If you agree I could do a pull request as well.

**Comment by markvincze** [comment]
Sounds great, feel free to issue a PR adding an example to the README.
